name = "smart-measure"
compatibility_date = "2025-12-18"
pages_build_output_dir = "./dist"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "smart-measure-db"
database_id = "6463d8f7-97cd-4d66-af26-84a0ed469c23"
